

import {
    PlusIcon,
    TrashIcon,
    PaperAirplaneIcon as SendIcon,
    ClockIcon as HistoryIcon,
    CodeBracketIcon,
    ClipboardDocumentIcon,
    CheckIcon,
    GlobeAltIcon,
    Bars3Icon as MenuIcon,
    XMarkIcon as XIcon,
    ArrowDownTrayIcon,
    ArrowPathIcon as SpinnerIcon,
    CommandLineIcon,
    RectangleStackIcon,
    QueueListIcon,
    ChevronRightIcon,
    ChevronDownIcon,
    ChevronDoubleLeftIcon,
    PencilIcon,
    ShareIcon,
    DocumentDuplicateIcon,
    XCircleIcon,
    // Fix: Added FolderIcon, FolderOpenIcon, and DocumentIcon to resolve missing export errors.
    FolderIcon,
    FolderOpenIcon,
    DocumentIcon,
} from '@heroicons/react/24/outline';

export {
    PlusIcon,
    TrashIcon,
    SendIcon,
    HistoryIcon,
    CodeBracketIcon,
    ClipboardDocumentIcon,
    CheckIcon,
    GlobeAltIcon,
    MenuIcon,
    XIcon,
    ArrowDownTrayIcon,
    SpinnerIcon,
    CommandLineIcon,
    RectangleStackIcon,
    QueueListIcon,
    ChevronRightIcon,
    ChevronDownIcon,
    ChevronDoubleLeftIcon,
    PencilIcon,
    ShareIcon,
    DocumentDuplicateIcon,
    XCircleIcon,
    FolderIcon,
    FolderOpenIcon,
    DocumentIcon,
};
